name: Build and Deploy React App

on:
  push:
    branches:
      - feat/linhvt/ci-cd

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: Install Dependencies
      run: 
        node -v
        npm -v
        npm install --force
    - name: Build React App
      run: 
        npm run build
        pwd
    - name: Whoami
      run: |
          whoami
          pwd
    - name: Deploy to server
      run: |
        cd /srv/frontend
        rsync -ahrz --delete-after -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./build .
    - name: Clean 
      run: rm -rf ~/.ssh
