name: Build and Deploy React App

on:
  push:
    branches:
      - feat/linhvt/ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install Dependencies
      run: npm install --force
    - name: Build React App
      run: npm run build 
    - name: Install SSH key
      run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo ${{secret.SSH_PRIVATE_KEY}} > ~/.ssh/id_rsa
          ssh-keyscan -H ${{secret.SSH_HOST}} >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
          ssh ${{secret.SSH_USER  }}@${{secret.SSH_HOST}} "cd ${{secret.WORD_DIR}} && git checkout {{secret.MAIN_BRANCH}}" && it pull ${{secret.MAIN_BRANCH}}
