name: Deploy

on:
  push:
    branches:
      - feat/linhvt/ci-cd

jobs:
  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest
    env:
      CI_USER: ubuntu 
      CI_IP: 192.168.99.75
      CI_PATH: /srv
      # CI_ENV_FILE: path/to/dev_env_file
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Create .env file
      #   run: cat ${{ env.CI_DEV_ENV_FILE }} > .env

      - name: Deploy to Development
        run: |
          rsync -ahrz --delete-after -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" ./build ${{ env.CI_USER }}@${{ env.CI_IP }}:${{ env.CI_PATH }}

    # Only run this job on the develop branch
    if: github.ref == 'refs/heads/main'
